Fixed JavaDoc issue
/home/vagrant/snacktory/src/main/java/de/jetwick/snacktory/ArticleTextExtractor.java:903: error: bad use of '>'
[error]      * www.test.airpr.com -> Won't work, always expect a topLevelPrivateDomain
[error]